import { AgentModel } from "@/models/agent-model";

export const agentSamples: AgentModel[] = [
  {
    id: "agent-001",
    active: true,
    name: "Customer Support Bot",
    description: "Handles customer inquiries and support tickets",
    model_id: "Grok-3",
    role: "support",
    prompt:
      "Assist customers with their queries in a friendly and professional manner.",
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-06-20T15:30:00Z"),
  },
  {
    id: "agent-002",
    active: false,
    name: "Sales Assistant",
    description: "Guides users through product purchases",
    model_id: "GPT-4o",
    role: "sales",
    prompt: "Provide product recommendations and assist with checkout.",
    createdAt: new Date("2025-02-15T12:00:00Z"),
    updatedAt: new Date("2025-05-10T09:00:00Z"),
  },
  {
    id: "agent-003",
    active: true,
    name: "Tech Support",
    description: "Resolves technical issues for users",
    model_id: "Llama-3.1",
    role: "tech-support",
    prompt: "Diagnose and troubleshoot technical problems efficiently.",
    createdAt: new Date("2025-03-01T08:00:00Z"),
    updatedAt: new Date("2025-06-22T14:00:00Z"),
  },
  {
    id: "agent-004",
    active: true,
    name: "Content Moderator",
    description: "Reviews and moderates user-generated content",
    model_id: "Claude-3.5",
    role: "moderator",
    prompt: "Ensure content complies with community guidelines.",
    createdAt: new Date("2025-04-05T16:00:00Z"),
    updatedAt: new Date("2025-06-15T11:00:00Z"),
  },
  {
    id: "agent-005",
    active: false,
    name: "FAQ Bot",
    description: "Answers frequently asked questions",
    model_id: "Grok-2",
    role: "faq",
    prompt: "Provide clear and concise answers to common questions.",
    createdAt: new Date("2025-01-20T09:00:00Z"),
    updatedAt: new Date("2025-03-25T13:00:00Z"),
  },
  {
    id: "agent-006",
    active: true,
    name: "Feedback Collector",
    description: "Gathers user feedback and suggestions",
    model_id: "Mistral-7B",
    role: "feedback",
    prompt: "Encourage users to provide constructive feedback.",
    createdAt: new Date("2025-02-28T11:00:00Z"),
    updatedAt: new Date("2025-06-10T10:00:00Z"),
  },
  {
    id: "agent-007",
    active: true,
    name: "Onboarding Assistant",
    description: "Helps new users get started",
    model_id: "GPT-3.5-turbo",
    role: "onboarding",
    prompt: "Guide new users through the platform's features.",
    createdAt: new Date("2025-03-15T14:00:00Z"),
    updatedAt: new Date("2025-06-18T12:00:00Z"),
  },
  {
    id: "agent-008",
    active: false,
    name: "Survey Bot",
    description: "Conducts user surveys",
    model_id: "Falcon-40B",
    role: "survey",
    prompt: "Engage users to complete surveys with clear questions.",
    createdAt: new Date("2025-04-10T10:00:00Z"),
    updatedAt: new Date("2025-05-20T16:00:00Z"),
  },
  {
    id: "agent-009",
    active: true,
    name: "Analytics Assistant",
    description: "Provides insights from data analytics",
    model_id: "Grok-3-mini",
    role: "analytics",
    prompt: "Summarize and explain data trends to users.",
    createdAt: new Date("2025-05-01T13:00:00Z"),
    updatedAt: new Date("2025-06-21T09:00:00Z"),
  },
  {
    id: "agent-010",
    active: true,
    name: "Event Coordinator",
    description: "Manages event registrations and updates",
    model_id: "Llama-3-70B",
    role: "event",
    prompt: "Assist users with event details and registration.",
    createdAt: new Date("2025-06-01T15:00:00Z"),
    updatedAt: new Date("2025-06-23T10:00:00Z"),
  },
];
