import {
  DashboardPermission,
  IAMPermission,
  RoleModel,
} from "@/models/role-model";

export const roleSamples: RoleModel[] = [
  {
    id: "role001",
    active: true,
    name: "Admin",
    dashboard: [DashboardPermission.View, DashboardPermission.Download],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
      IAMPermission.Delete,
      IAMPermission.Download,
    ],
    createdAt: new Date("2024-10-01T08:00:00Z"),
    updatedAt: new Date("2025-06-15T16:00:00Z"),
  },
  {
    id: "role002",
    active: true,
    name: "Editor",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
    ],
    createdAt: new Date("2024-11-10T10:30:00Z"),
    updatedAt: new Date("2025-05-20T12:45:00Z"),
  },
  {
    id: "role003",
    active: false,
    name: "Viewer",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View],
    knowledgeBase: [IAMPermission.View],
    createdAt: new Date("2024-12-01T14:15:00Z"),
    updatedAt: new Date("2025-03-10T09:20:00Z"),
  },
  {
    id: "role004",
    active: true,
    name: "Content Manager",
    dashboard: [DashboardPermission.View, DashboardPermission.Download],
    analytics: [DashboardPermission.View],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
      IAMPermission.Download,
    ],
    createdAt: new Date("2025-01-05T11:00:00Z"),
    updatedAt: new Date("2025-06-10T15:30:00Z"),
  },
  {
    id: "role005",
    active: true,
    name: "Analyst",
    dashboard: [DashboardPermission.View, DashboardPermission.Download],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [IAMPermission.View, IAMPermission.Download],
    createdAt: new Date("2024-09-15T13:45:00Z"),
    updatedAt: new Date("2025-04-25T10:10:00Z"),
  },
  {
    id: "role006",
    active: true,
    name: "Support Agent",
    dashboard: [DashboardPermission.View],
    analytics: [],
    knowledgeBase: [IAMPermission.View, IAMPermission.Download],
    createdAt: new Date("2025-02-20T09:25:00Z"),
    updatedAt: new Date("2025-06-01T11:50:00Z"),
  },
  {
    id: "role007",
    active: false,
    name: "Guest",
    dashboard: [],
    analytics: [],
    knowledgeBase: [IAMPermission.View],
    createdAt: new Date("2024-08-20T16:00:00Z"),
    updatedAt: new Date("2025-02-28T14:00:00Z"),
  },
  {
    id: "role008",
    active: true,
    name: "Developer",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
    ],
    createdAt: new Date("2025-03-01T12:30:00Z"),
    updatedAt: new Date("2025-06-12T17:15:00Z"),
  },
  {
    id: "role009",
    active: true,
    name: "Marketing",
    dashboard: [DashboardPermission.View, DashboardPermission.Download],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [IAMPermission.View, IAMPermission.Download],
    createdAt: new Date("2024-12-15T10:50:00Z"),
    updatedAt: new Date("2025-05-05T13:25:00Z"),
  },
  {
    id: "role010",
    active: true,
    name: "HR Manager",
    dashboard: [DashboardPermission.View],
    analytics: [],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
      IAMPermission.Delete,
    ],
    createdAt: new Date("2025-02-10T08:40:00Z"),
    updatedAt: new Date("2025-06-15T22:00:00Z"),
  },
];
