import {
  DashboardPermission,
  IAMPermission,
  RoleModel,
} from "@/models/role-model";

export const roleSamples: RoleModel[] = [
  {
    id: "1",
    status: "Active",
    name: "SuperAdmin",
    dashboard: [DashboardPermission.View, DashboardPermission.Download],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Delete,
      IAMPermission.Edit,
      IAMPermission.Download,
    ],
    createdAt: new Date("2025-01-01T10:00:00.000Z"),
    updatedAt: new Date("2025-06-15T14:54:00.000Z"),
  },
  {
    id: "2",
    status: "Active",
    name: "Editor",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
    ],
    createdAt: new Date("2024-12-15T09:15:00.000Z"),
    updatedAt: new Date("2025-03-20T14:45:00.000Z"),
  },
  {
    id: "3",
    status: "Inactive",
    name: "Viewer",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [IAMPermission.View],
    createdAt: new Date("2025-02-10T11:20:00.000Z"),
    updatedAt: new Date("2025-05-25T16:10:00.000Z"),
  },
  {
    id: "4",
    status: "Active",
    name: "ContentManager",
    dashboard: [DashboardPermission.View],
    analytics: [],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Delete,
    ],
    createdAt: new Date("2024-11-05T08:30:00.000Z"),
    updatedAt: new Date("2025-06-10T10:00:00.000Z"),
  },
  {
    id: "5",
    status: "Inactive",
    name: "Contributor",
    dashboard: [],
    analytics: [DashboardPermission.View],
    knowledgeBase: [IAMPermission.View, IAMPermission.Create],
    createdAt: new Date("2025-03-01T13:40:00.000Z"),
    updatedAt: new Date("2025-04-15T15:25:00.000Z"),
  },
  {
    id: "6",
    status: "Active",
    name: "Admin",
    dashboard: [DashboardPermission.View, DashboardPermission.Download],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
      IAMPermission.Delete,
    ],
    createdAt: new Date("2024-10-20T07:50:00.000Z"),
    updatedAt: new Date("2025-06-12T09:35:00.000Z"),
  },
  {
    id: "7",
    status: "Active",
    name: "Moderator",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [IAMPermission.View, IAMPermission.Edit],
    createdAt: new Date("2025-04-05T14:55:00.000Z"),
    updatedAt: new Date("2025-05-30T11:20:00.000Z"),
  },
  {
    id: "8",
    status: "Inactive",
    name: "Guest",
    dashboard: [DashboardPermission.View],
    analytics: [],
    knowledgeBase: [IAMPermission.View],
    createdAt: new Date("2024-09-10T06:25:00.000Z"),
    updatedAt: new Date("2025-02-28T13:50:00.000Z"),
  },
  {
    id: "9",
    status: "Active",
    name: "Publisher",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [
      IAMPermission.View,
      IAMPermission.Create,
      IAMPermission.Edit,
    ],
    createdAt: new Date("2025-05-15T12:10:00.000Z"),
    updatedAt: new Date("2025-06-14T08:40:00.000Z"),
  },
  {
    id: "10",
    status: "Active",
    name: "Analyst",
    dashboard: [DashboardPermission.View],
    analytics: [DashboardPermission.View, DashboardPermission.Download],
    knowledgeBase: [IAMPermission.View],
    createdAt: new Date("2024-08-01T15:00:00.000Z"),
    updatedAt: new Date("2025-06-15T14:54:00.000Z"),
  },
];
