version: 2.1

orbs:
  go: circleci/go@1.7.3

jobs:
  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - go/install-go:
          version: 1.21
      - run:
          name: Install Dependencies
          command: go run main.go

workflows:
  test_and_build:
    jobs:
      - test
