version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage

workflows:
  test_and_build:
    jobs:
      - test
